<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: options.proto

namespace GPBMetadata;

class Options
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
A
options.protoclient google/protobuf/descriptor.protobproto3'
        , true);

        static::$is_initialized = true;
    }
}

