<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timestamp.proto

namespace GPBMetadata;

class Timestamp
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad7010a0f74696d657374616d702e70726f746f120f676f6f676c652e70" .
            "726f746f627566222b0a0954696d657374616d70120f0a077365636f6e64" .
            "73180120012803120d0a056e616e6f73180220012805427e0a13636f6d2e" .
            "676f6f676c652e70726f746f627566420e54696d657374616d7050726f74" .
            "6f50015a2b6769746875622e636f6d2f676f6c616e672f70726f746f6275" .
            "662f7074797065732f74696d657374616d70f80101a20203475042aa021e" .
            "476f6f676c652e50726f746f6275662e57656c6c4b6e6f776e5479706573" .
            "620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

