<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

namespace GPBMetadata;

class Types
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Options::initOnce();
        $pool->internalAddGeneratedFile(
            '
Á
types.protoAElf.protobuf.generatedoptions.proto"#
StringInput
string_value (	"
	MinerList
pubkeys ("
Hash
value ("
Address
value ("è
Transaction6
from_address (2 .AElf.protobuf.generated.Address4

to_address (2 .AElf.protobuf.generated.Address
ref_block_number (
ref_block_prefix (
method_name (	
params (
	signatureN ("¤
ElectionVotingRecord/
voter (2 .AElf.protobuf.generated.Address
	candidate (	
amount (
term_number (.
vote_id (2.AElf.protobuf.generated.Hash
	lock_time (4
unlock_timestamp (2.google.protobuf.Timestamp6
withdraw_timestamp (2.google.protobuf.Timestamp2
vote_timestamp	 (2.google.protobuf.Timestamp
is_withdrawn
 (
weight (
is_change_target ("ƒ
ElectorVote?
active_voting_record_ids (2.AElf.protobuf.generated.HashB
withdrawn_voting_record_ids (2.AElf.protobuf.generated.Hash!
active_voted_votes_amount (
all_voted_votes_amount (L
active_voting_records (2-.AElf.protobuf.generated.ElectionVotingRecordN
withdrawn_votes_records (2-.AElf.protobuf.generated.ElectionVotingRecord
pubkey ("»
CandidateVoteH
!obtained_active_voting_record_ids (2.AElf.protobuf.generated.HashK
$obtained_withdrawn_voting_record_ids (2.AElf.protobuf.generated.Hash*
"obtained_active_voted_votes_amount (\'
all_obtained_voted_votes_amount (U
obtained_active_voting_records (2-.AElf.protobuf.generated.ElectionVotingRecordW
 obtained_withdrawn_votes_records (2-.AElf.protobuf.generated.ElectionVotingRecord
pubkey ("9
ContractDeploymentInput
category (
code ("V
ContractUpdateInput1
address (2 .AElf.protobuf.generated.Address
code ("¢
CrossChainTransferInput,
to (2 .AElf.protobuf.generated.Address
symbol (	
amount (
memo (	
to_chain_id (
issue_chain_id ("P

MerklePathB
merkle_path_nodes (2\'.AElf.protobuf.generated.MerklePathNode"Y
MerklePathNode+
hash (2.AElf.protobuf.generated.Hash
is_left_child_node ("¯
CrossChainReceiveTokenInput
from_chain_id (
parent_chain_height ("
transfer_transaction_bytes (8
merkle_path (2#.AElf.protobuf.generated.MerklePath"#
GetTokenInfoInput
symbol (	"R
GetBalanceInput
symbol (	/
owner (2 .AElf.protobuf.generated.Address"d
GetBalanceOutput
symbol (	/
owner (2 .AElf.protobuf.generated.Address
balance ("h

IssueInput
symbol (	
amount (
memo (	,
to (2 .AElf.protobuf.generated.Address"k
TransferInput,
to (2 .AElf.protobuf.generated.Address
symbol (	
amount (
memo (	"Ÿ
TransferFromInput.
from (2 .AElf.protobuf.generated.Address,
to (2 .AElf.protobuf.generated.Address
symbol (	
amount (
memo (	"7
TransactionFeeCharged
symbol (	
amount ("r
ResourceTokenCharged
symbol (	
amount (:
contract_address (2 .AElf.protobuf.generated.Address"Ö
	TokenInfo
symbol (	

token_name (	
supply (
total_supply (
decimals (0
issuer (2 .AElf.protobuf.generated.Address
is_burnable (
issue_chain_id (
issued	 ("´
Transferred5
from (2 .AElf.protobuf.generated.AddressBˆõ3
to (2 .AElf.protobuf.generated.AddressBˆõ
symbol (	Bˆõ
amount (
memo (	: »"Ö
CrossChainTransferred.
from (2 .AElf.protobuf.generated.Address,
to (2 .AElf.protobuf.generated.Address
symbol (	
amount (
memo (	
to_chain_id (
issue_chain_id (: »"²
CrossChainReceived.
from (2 .AElf.protobuf.generated.Address,
to (2 .AElf.protobuf.generated.Address
symbol (	
amount (
memo (	
from_chain_id (
issue_chain_id (
parent_chain_height (>
transfer_transaction_id	 (2.AElf.protobuf.generated.Hash: »bproto3'
        , true);

        static::$is_initialized = true;
    }
}

